#ifndef TSGRAPH__CSRC_PYOBJ_OPERATORS_H_
#define TSGRAPH__CSRC_PYOBJ_OPERATORS_H_

#define PY_SSIZE_T_CLEAN
#include <Python.h>

#include "api/py_graph_impl.h"

#define NODE_OPERATOR_DECL(op) PyObject *node_ref_##op(PyObject *self, PyObject *args);

NODE_OPERATOR_DECL(ADD)
NODE_OPERATOR_DECL(SUB)
NODE_OPERATOR_DECL(MUL)
NODE_OPERATOR_DECL(DIV)
NODE_OPERATOR_DECL(MOD)

NODE_OPERATOR_DECL(AND)
NODE_OPERATOR_DECL(OR)
NODE_OPERATOR_DECL(XOR)

NODE_OPERATOR_DECL(EQU)
NODE_OPERATOR_DECL(NEQ)
NODE_OPERATOR_DECL(LEQ)
NODE_OPERATOR_DECL(GEQ)
NODE_OPERATOR_DECL(LE)
NODE_OPERATOR_DECL(GE)

#endif // TSGRAPH__CSRC_PYOBJ_OPERATORS_H_
