name: "Type Check"

on: [push]

jobs:
  check_types:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install mypy
        run: |
          pip install mypy
      - name: Build Package
        run: |
          pip install -r requirements.txt
          pip install .
      - name: Run Checks
        run: |
          mypy tsgraph
