name: "Static Type Check"

on: [push]

jobs:
  check_types:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install mypy
        run: |
          pip install mypy
      - name: Build Package
        run: |
          pip install .
      - name: Run Checks
        run: |
          mypy tsgraph
